version: '3'
services:
  app:
    container_name: gin
    environment:
      - PORT=${PORT}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
      - DATABASE_PORT=${DB_PORT}
      - DB_URL=${DB_URL}
      - TOKEN_HOUR_LIFESPAN=${TOKEN_HOUR_LIFESPAN}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - API_SECRET=${API_SECRET}
      - RABBITMQ_ADDRESS=${RABBITMQ_ADDRESS}
    tty: true
    build: .
    ports:
      - 3005:3005
    restart: on-failure
    volumes:
      - ./:/go/bin/app:cached
    depends_on:
      - db
      - redis
      - rabbitmq

  db:
    image: postgres:latest
    container_name: postgres-topics
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - '5432:5432'
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7.0-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass redistestpass
    volumes: 
      - redis:/data

  rabbitmq:
    image: rabbitmq:3.9-alpine
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

volumes:
  pg_data:
  redis:
    driver: local

