apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-volumes
  labels:
    app: topics
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
  persistentVolumeReclaimPolicy: Retain
