# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: topics-service
  namespace: default
spec:
  selector:
    app: topics
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 3005
    targetPort: 3005
    nodePort: 30000
---

